---
title: "Exploring the Central Limit Theorem with the exponential distribution"
author: "Dave Patterson"
date: "September 20, 2015"
output: html_document
---

## Overview: 

I will investigate the exponential distribution and compare it with the Central Limit Theorem. 
To do this, I will compare some sample means and variances to their theoretical values. 
I will also compare the distribution of a large collection of random exponentials and the 
distribution of a large collection of averages of 40 exponentials.

## Simulations: 
Include English explanations of the simulations you ran, with the accompanying R code.
Your explanations should make clear what the R code accomplishes.
## Sample Mean versus Theoretical Mean: 
Include figures with titles. In the figures, highlight the means you are comparing. 
Include text that explains the figures and what is shown on them, and provides
appropriate numbers.
## Sample Variance versus Theoretical Variance: 
Include figures (output from R) with titles. Highlight the variances you are comparing. 
Include text that explains your understanding of the differences of the variances.
## Distribution: 
Via figures and text, explain how one can tell the distribution is approximately normal.